import type { Metadata } from "next";
import "./globals.css";
import { ModalProvider } from "@/providers/ModalProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ModalProvider>
      <body>{children}</body>
      </ModalProvider>
    </html>
  );
}
